/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArticleStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Article = IDL.Record({
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'readingTime' : IDL.Nat,
  'body' : IDL.Text,
  'publishedDate' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'authorRole' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'excerpt' : IDL.Text,
  'coverAlt' : IDL.Text,
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleInput = IDL.Record({
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'readingTime' : IDL.Nat,
  'body' : IDL.Text,
  'publishedDate' : IDL.Text,
  'slug' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'authorRole' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'excerpt' : IDL.Text,
  'coverAlt' : IDL.Text,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__articles' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, Article))],
      ['query'],
    ),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([ArticleInput], [Article], []),
  'deleteArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], []),
  'getArticlesByTag' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getPublishedArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllArticles' : IDL.Func([], [IDL.Vec(Article)], []),
  'listPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'updateArticle' : IDL.Func([IDL.Text, ArticleInput], [IDL.Opt(Article)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArticleStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Article = IDL.Record({
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'readingTime' : IDL.Nat,
    'body' : IDL.Text,
    'publishedDate' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'authorRole' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'excerpt' : IDL.Text,
    'coverAlt' : IDL.Text,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleInput = IDL.Record({
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'readingTime' : IDL.Nat,
    'body' : IDL.Text,
    'publishedDate' : IDL.Text,
    'slug' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'authorRole' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'excerpt' : IDL.Text,
    'coverAlt' : IDL.Text,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__articles' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, Article))],
        ['query'],
      ),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([ArticleInput], [Article], []),
    'deleteArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], []),
    'getArticlesByTag' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getPublishedArticle' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllArticles' : IDL.Func([], [IDL.Vec(Article)], []),
    'listPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'updateArticle' : IDL.Func(
        [IDL.Text, ArticleInput],
        [IDL.Opt(Article)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };