/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'status' : ArticleStatus,
  'title' : string,
  'readingTime' : bigint,
  'body' : string,
  'publishedDate' : string,
  'slug' : string,
  'tags' : Array<string>,
  'authorName' : string,
  'authorRole' : string,
  'coverImage' : [] | [ExternalBlob],
  'excerpt' : string,
  'coverAlt' : string,
}
export interface ArticleInput {
  'status' : ArticleStatus,
  'title' : string,
  'readingTime' : bigint,
  'body' : string,
  'publishedDate' : string,
  'slug' : [] | [string],
  'tags' : Array<string>,
  'authorName' : string,
  'authorRole' : string,
  'coverImage' : [] | [ExternalBlob],
  'excerpt' : string,
  'coverAlt' : string,
}
export type ArticleStatus = { 'published' : null } |
  { 'draft' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__articles' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Article]>
  >,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  /**
   * / Object-storage mixin — provides `_immutableObjectStorage*` certificate
   * / methods required for cover-image uploads.
   */
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[ArticleInput], Article>,
  'deleteArticle' : ActorMethod<[string], [] | [Article]>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getArticle' : ActorMethod<[string], [] | [Article]>,
  'getArticlesByTag' : ActorMethod<[[] | [string]], Array<Article>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestArticles' : ActorMethod<[bigint], Array<Article>>,
  'getPublishedArticle' : ActorMethod<[string], [] | [Article]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllArticles' : ActorMethod<[], Array<Article>>,
  'listPublishedArticles' : ActorMethod<[], Array<Article>>,
  'updateArticle' : ActorMethod<[string, ArticleInput], [] | [Article]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];